var nom =prompt ('Saisissez votre nom');
alert (nom);
var prenom=prompt ("Saisissez votre prénom");
alert (prenom);
var nb1=prompt ("Entrez un nombre");
alert (nb1);
var nb2=prompt ("Entrez un deuxième nombre");
alert (nb2);
var produit=nb1*nb2;
alert ("le produit de ces deux nombres est: "+produit);
var temp=prompt ("Entrez la température en degré celtius");
var temp2=(temp*9/5)+32;
alert ("la température en Fahrenheit est: "+temp2);
